pipeline {
  agent {
    kubernetes {
      label 'kuber-heml'
      defaultContainer 'helm'
    }
  }
  stages {
    stage('Deploy') {
      steps {
          sh 'helm version'
          sh 'kubectl get nodes'
          sh 'helm upgrade --install flask-app charts/flask-app -n formazione-sou'
      }
    }
  }
}