name: flask-app
replicas: 2

LabelKey: app
LabelValue: flask-app

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

containers:
  name: flask-app
  image: andry67/helloworld
  tag: latest
  imagePullPolicy: IfNotPresent
  port: 5000
  protocol: TCP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

ingress-nginx:
  enabled: true
  controller:
    service:
      type: NodePort
    ingressClassResource:
      name: nginx-flask-app
      default: true

Ingress:
  IngressClassName: nginx
  host: formazionesou.local
  path: /
  pathType: Prefix
  service:
    port: 80

ClusterIP:
  name: service-flask-app
  servicePort: 80
  targetPort: 5000

