def buildAndPushTag(Map args) {

  def defaults = [
    registryUrl: 'docker.io',
    credRegistry: 'credenziali-dockerhub',
    dockerfileDir: "./build-push-image",
    dockerfileName: "Dockerfile",
    buildArgs: "",
    pushLatest: true
  ]

  args = defaults + args

  withCredentials([usernamePassword(
    credentialsId: args.credRegistry,
    usernameVariable: 'USER',
    passwordVariable: 'PASS'
  )]) {
  sh 'echo "$PASS" | docker login ' + args.registryUrl + ' -u "$USER" --password-stdin'
  sh "docker build ${args.buildArgs} -t ${args.image}:${args.buildTag} -f ${args.dockerfileDir}/${args.dockerfileName} ${args.dockerfileDir}"
  sh "docker push ${args.image}:${args.buildTag}"
    
    if (args.pushLatest) {
      sh "docker tag ${args.image}:${args.buildTag} ${args.image}:latest"
      sh "docker push ${args.image}:latest"
      sh "docker rmi --force ${args.image}:latest"
    }

  sh "docker rmi --force ${args.image}:${args.buildTag}"
  sh "docker logout ${args.registryUrl}"
  return "${args.image}:${args.buildTag}"
  }
}

pipeline {
  agent any

  stages {
    stage('Avvia Docker daemon') {
      steps {
        sh '''
        sudo dockerd > /tmp/dockerd.log 2>&1 &
        sleep 10
        '''
      }
    }
    stage('Build & Push') {
      steps {
        script {
          def ref = buildAndPushTag(
            image: 'andry67/helloworld',
            buildTag: "${env.BUILD_NUMBER}",
            pushLatest: false
          )
          echo "Immagine pubblicata: ${ref}"
        }
      }
    }
  }
}
