apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ .Values.LabelKey }}: {{ .Values.LabelValue }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
      maxSurge: {{ .maxSurge }}
      maxUnavailable: {{ .maxUnavailable }}
    {{- end }}
{{- end }}
  template:
    metadata:
      labels:
        {{ .Values.LabelKey }}: {{ .Values.LabelValue }}
    spec:
      containers:
        {{- with .Values.containers }}
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - containerPort: {{ .port }}
              protocol: {{ .protocol }}
          {{- with .resources }}
          resources:
            requests:
              cpu: {{ .requests.cpu }}
              memory: {{ .requests.memory }}
            limits:
              cpu: {{ .limits.cpu }}
              memory: {{ .limits.memory }}
          {{- end }}
          {{- with .readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $.Values.containers.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- with .livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .path }}
              port: {{ $.Values.containers.port }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}