apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  {{- with .Values.Ingress }}
  ingressClassName: {{ .IngressClassName }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.ClusterIP.name }}
                port:
                  number: {{ .service.port}}
  {{- end}}