server {
    listen 80;
    server_name localhost;

    location / {
        auth_basic           "Area riservata";          
        auth_basic_user_file /etc/nginx/auth/.htpasswd; 
        root  /usr/share/nginx/html;
        index index.html;
    }
}