---
- name: Configurazione agent jenkins
  hosts: server
  become: true

  tasks:
    - name: Crea il volume dell'agent
      containers.podman.podman_volume:
        name: jenkins-agent-data
        state: present

    - name: Avvia l'agent jenkins
      containers.podman.podman_container:
        name: jenkins-agent
        image: img
        user: root
        pull: never
        network: network_1
        ip: "10.0.0.3"
        privileged: true
        volumes:
          - "jenkins-agent-data:/home/jenkins/agent"
          - "/run/podman/podman.sock:/var/run/podman.sock"
        env:
          JENKINS_URL: "http://10.0.0.2:8080"
          JENKINS_AGENT_NAME: agent-1
          JENKINS_SECRET: "{{ segreto }}"
          JENKINS_AGENT_WORKDIR: /home/jenkins/agent
          CONTAINER_HOST: "unix:///var/run/podman.sock"
        state: started